spring:
  application:
    name: mall-coupon
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.189.129:3305/mall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 8111

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto



server:
  port: 7000

management:
  endpoints:
    web:
      exposure:
        include: '*'
