spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8111

  redis:
    host: 192.168.189.129
    port: 6379

  rabbitmq:
    virtual-host: /
    host: 192.168.189.129
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
server:
  port: 15000
management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true
