spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 8111
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.189.129
  session:
    store-type: redis

server:
  port: 20000

management:
  endpoints:
    web:
      exposure:
        include: '*'


