spring:
  application:
    name: mall-thirdparty
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 8111
    alicloud:
      access-key: ***************
      secret-key: ***************
      oss:
        endpoint: oss-ap-southeast-3.aliyuncs.com
        bucket: project-mall-test
server:
  port: 30000



management:
  endpoints:
    web:
      exposure:
        include: '*'
